// This model is generated by some OPL code out of SEND+MORE==MONEY
using CP;

range r=0..9;
range rwithout0=1..9;
dvar int S in rwithout0;
dvar int M in rwithout0;
dvar int E in r;
dvar int N in r;
dvar int D in r;
dvar int O in r;
dvar int R in r;
dvar int Y in r;

dvar int SEND;
dvar int MORE;
dvar int MONEY;

subject to {
SEND+MORE==MONEY;

SEND == 1000*S+100*E+10*N+1*D;
MORE == 1000*M+100*O+10*R+1*E;
MONEY == 10000*M+1000*O+100*N+10*E+1*Y;

allDifferent(append(S,E,N,D,M,O,R,Y));
}

execute {
writeln("SEND = ",SEND);
writeln("MORE = ",MORE);
writeln("MONEY = ",MONEY);
}
